CREATE DATABASE Hospital
GO
USE Hospital
GO

CREATE TABLE GP
(
	GP_ID INT PRIMARY KEY,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	[ADDRESS] VARCHAR(40) NOT NULL,
	PHONE VARCHAR(30)
)

CREATE TABLE PATIENT
(
	PATIENT_ID INT PRIMARY KEY,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	GENDER CHAR(1) NOT NULL CHECK(GENDER = 'M' OR GENDER = 'F'),
	BIRTHDATE DATE NOT NULL,
	EGN VARCHAR(10) NOT NULL UNIQUE,
	GP_ID INT NOT NULL REFERENCES GP(GP_ID)
)

INSERT INTO GP(GP_ID, FNAME, LNAME, [ADDRESS])
VALUES(1, 'Nikola', 'Tsolev', 'bul. Bulgaria')

INSERT INTO PATIENT
VALUES(1, 'Penka', 'Koleva', 'F', '2001-12-18', '0182663209', 1)

SELECT * FROM GP
SELECT * FROM PATIENT
