CREATE DATABASE University
GO
USE University
GO


CREATE TABLE Students
(
	F_NUM VARCHAR(10) PRIMARY KEY,
	[NAME] VARCHAR(50) NOT NULL,
	PHONE VARCHAR(15),
	GENDER CHAR(1) CHECK(GENDER = 'M' OR GENDER = 'F')
)

CREATE TABLE Courses
(
	COURSE_ID INT PRIMARY KEY,
	[NAME] VARCHAR(100) NOT NULL,
	HORARIUM INT NOT NULL CHECK(HORARIUM > 10 AND HORARIUM < 100),
	[START_DATE] DATE CHECK([START_DATE] > '2023-10-01'),
	END_DATE DATE
)

CREATE TABLE Student_Courses
(
	COURSE_ID INT NOT NULL REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	F_NUM VARCHAR(10) NOT NULL REFERENCES STUDENTS(F_NUM) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(COURSE_ID, F_Num)
)

INSERT INTO Students(F_NUM, [NAME], GENDER)
VALUES('2401321099', 'Georgi Georgiev', 'M')

INSERT INTO Courses
VALUES(1, 'Databases', 23, '2025-06-14', '2025-06-29')

INSERT INTO Student_Courses
VALUES(1, '2401321099')

UPDATE Courses
SET HORARIUM = HORARIUM + 10

SELECT DATEDIFF(WEEK, [START_DATE], END_DATE) AS [DIFFERENCE] FROM Courses

DELETE FROM STUDENTS
WHERE F_NUM = '2401321099'
